# Generated by Django 3.2.8 on 2021-11-01 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tessiu_inflamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessiu',
            name='inflamation',
            field=models.FloatField(blank=True, null=True, verbose_name='Inflamación'),
        ),
    ]
