# Generated by Django 3.2.8 on 2021-11-08 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_tessiu_inflamation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tessiu',
            name='inflamation',
            field=models.FloatField(default=0, verbose_name='Inflamación'),
            preserve_default=False,
        ),
    ]
